packages:
  - "ctf/packages/agent-mcp-server"
  - "ctf/packages/economic-models"
  - "ctf/packages/eol"
  - "ctf/packages/mobile"
  - "ctf/packages/plugin-education"
  - "ctf/packages/pm-mcp-server"
  - "ctf/packages/shared"
  - "ctf/packages/web"
  - "landing-page"
  - "platform"
  - "waitlist-landing-page"
  - "wiki-blog"
